version: '3.1'

services:
  arangodb:
    image: arangodb:3.9
    environment:
      - ARANGO_NO_AUTH=1
    #ports:
    #  - 8529:18529


  flowsync:
    build:
      context: ./docks/flowsync
    image: flowsync:0.1.0
    ports:
      - 12000:12000
    depends_on:
      - arangodb

  flow:
    build:
      context: ./docks/flow
    image: flow:0.1.0
    ports:
      - 3000:3000
    depends_on:
      - flowsync
      - arangodb
